CREATE SEQUENCE INSCRIPCION.seq_categoria MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_correo MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_estado MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_formulario MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_formulario_inscripcion MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_inscripcion MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_inscripcion_usuario MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_menu MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_modalidad MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_notificacion MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_organismo MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_organismo_cagetoria MINVALUE 1 START WITH 50 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_permiso MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_permiso_menu MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_rol MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_rol_permiso MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_sector MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_sede MINVALUE 1 START WITH 50 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_tipo MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_usuario MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_usuario_organismo_categoria MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_vigencia MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_instancia MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_clase MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_clase_usuario MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;

CREATE SEQUENCE INSCRIPCION.seq_clase_alumno MINVALUE 1 START WITH 10 INCREMENT BY 1 CACHE 20;