ALTER TABLE INSCRIPCION.FORMULARIO_INSCRIPCION ADD DIRIGIDO NUMERIC(1) DEFAULT  1;

ALTER TABLE INSCRIPCION.FORMULARIO_INSCRIPCION ADD ESTADO NUMERIC(1) DEFAULT 1;

ALTER TABLE INSCRIPCION.FORMULARIO drop column DIRIGIDO;

COMMIT;


ALTER TABLE INSCRIPCION.FORMULARIO ADD DIRIGIDO NUMERIC(1) DEFAULT 1;

COMMIT;