INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Colegio Nº 02 DE 01 Domingo Faustino Sarmiento', 'LIBERTAD 1257', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 'Colegio Nº 04 DE 09 Nicolás Avellaneda', 'EL SALVADOR 5528', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(3, 'Colegio Nº 06 DE 02 Manuel Belgrano', 'ECUADOR 1158', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(4, 'Colegio Nº 18 DE 18 Dr. Alberto Larroque', 'MORON 4149', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(5, 'Esc. de Comercio Nº 05 DE 03 José de San Martín', 'AV. ENTRE RIOS 757', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(6, 'Esc. de Comercio Nº 06 DE 13 América', 'AV. ESCALADA 2890', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(7, 'Esc. de Comercio Nº 11 DE 17 Dr. José Peralta', 'PEDRO LOZANO 4250', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(8, 'Esc. de Comercio Nº 15 DE 15 Dra. Cecilia Grierson', 'VALDENEGRO 3523', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(9, 'Esc. de Comercio Nº 35 DE 21 Leopoldo Marechal', 'AV.LARRAZABAL 5140', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(10, 'Esc. de Educacion Media Nº 01 DE 14 Federico García Lorca', 'AV.CHORROARIN 305', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(11, 'Esc. de Educacion Media Nº 02 DE 16', 'Zamudio 4386', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(12, 'Esc. de Educacion Media Nº 02 DE 19 Arturo Jauretche', 'MARTINEZ CASTRO 3067', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(13, 'Esc. de Educacion Media Nº 02 DE 20', 'CAÑADA DE GOMEZ 3850', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(14, 'Esc. de Educación Media Nº 03 DE 04', 'PALOS Y JUAN MANUEL BLANES S/N', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(15, 'Esc. de Educacion Media Nº 04 DE 19 Homero Manzi', 'AV. SAENZ 631', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(16, 'Esc. de Educacion Media Nº 06 DE 01 Padre Carlos Mugica', 'LETONIA Y ANTARTIDA ARGENTINA S/N', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(17, 'Esc. de Educación Media Nº 06 DE 05', 'AV.MONTESQUIEU E IRIARTE S/N', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(18, 'Esc. Normal Superior N° 07 José María Torres / Esc. de Comercio Nº 08 DE 02 Patricias Argentinas', 'AV.CORRIENTES 4261', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(19, 'Esc. Técnica Nº 01 DE 04 Ing. Otto Krause', 'PASEO COLON AV. 650', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(20, 'Esc. Técnica Nº 08 DE 13 Paula Albarracin de Sarmiento', 'COLLIVADINO, PIO 436', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(21, 'Esc. Técnica Nº 09 DE 07 Ing. Luis A. Huergo', 'GAINZA, MARTIN DE, GRAL. 1050', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(22, 'Esc. Técnica Nº 09 DE 07 Ing. Luis A. Huergo (TALLER)', 'GAINZA, MARTIN DE, GRAL. 1050', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(23, 'Esc. Técnica Nº 11 DE 06 Manuel Belgrano', 'COCHABAMBA 2830', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(24, 'Esc. Técnica Nº 13 DE 21 Ing. Jose Luis Delpini', 'CHILAVERT, MARTINIANO, CORONEL 5460', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(25, 'Esc. Técnica Nº 19 DE 01 Alejandro Volta', 'LAVALLE 1681 CASI R.PEÑA ', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(26, 'Esc. Técnica Nº 24 DE 17 Defensa de Buenos Aires', 'GUTIERREZ, RICARDO 3246', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(27, 'Esc. Técnica Nº 31 DE 04 Maestro Quinquela', 'DON PEDRO DE MENDOZA AV. 1777', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(28, 'Esc. Técnica Nº 32 DE 14 Gral. Jose de San Martin', 'GARCIA, TEODORO 3899', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(29, 'Esc. Técnica Nº 33 DE 19 Fundición Maestranza del Plumerillo (MATERIAS)', 'RABANAL, FRANCISCO, INTENDENTE AV. 1549', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(30, 'Esc. Técnica Nº 33 DE 19 Fundición Maestranza del Plumerillo (TALLER)', 'RABANAL, FRANCISCO, INTENDENTE AV. 1549', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(31, 'Esc. Técnica Nº 36 DE 15 Alte. Guillermo Brown', 'GALVAN 3710', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(32, 'Escuela Normal Superior en Lenguas Vivas N° 1  " Roque Sáenz Peña "', 'AV. CÓRDOBA 1951', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(33, 'Escuelas Técnicas Raggio', 'DEL LIBERTADOR AV. 8635', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(34, 'ESEA en Artes Visuales Manuel Belgrano', 'WENCESLAO VILLAFAÑE 1342', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(35, 'ESEA en Teatro Nini Marshall', 'OLIDEN 1245', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(36, 'IES en Lenguas Vivas Juan Ramón Fernández', 'CARLOS PELLEGRINI 1515', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(37, 'Liceo Nº 05 DE 11 Pascual Guaglianone', 'AV. CARABOBO 286', '', '', '', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);