-- --------------------------------------
-- CATEGORIAS
-- --------------------------------------
INSERT INTO CATEGORIA(ID,NOMBRE,NIVEL,PADRE_ID,SEQ,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES (1,'CAI',0,0,0,CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);

INSERT INTO CATEGORIA(ID,NOMBRE,NIVEL,PADRE_ID,SEQ,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES (2,'Clud De Chicos',0,0,0,CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);

INSERT INTO CATEGORIA(ID,NOMBRE,NIVEL,PADRE_ID,SEQ,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES (3,'Coros',0,0,0,CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);

INSERT INTO CATEGORIA(ID,NOMBRE,NIVEL,PADRE_ID,SEQ,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES (4,'Orquesta',0,0,0,CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);

INSERT INTO CATEGORIA(ID,NOMBRE,NIVEL,PADRE_ID,SEQ,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES (5,'Red de fortalecimiento Nivel Secundario',0,0,0,CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);


-- --------------------------------------
-- ORGANISMOS
-- --------------------------------------
INSERT INTO ORGANISMO (ID, NOMBRE, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES (1,'Educación',CURRENT_DATE,'ADMIN',CURRENT_DATE,'ADMIN',1);


-- --------------------------------------
-- ORGANISMO_CATEGORIA
-- --------------------------------------
INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES (1,1,1,1);

INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES (2,1,2,1);

INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES (3,1,3,1);

INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES (4,1,4,1);

INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES (5,1,5,1);
