import {
  FIRST_NAME, LAST_NAME, DOCUMENT_NATIONALITY,
  DOCUMENT_NUMBER, GENDER, BIRTHDAY, PROVINCE,
  LOCATION, ADDRESS, FLOOR, DEPARTMENT, POSTAL_CODE,
  CODE_PHONE, AREA_CODE_PHONE, PHONE, CODE_CELLPHONE,
  AREA_CODE_CELLPHONE, CELLPHONE, CUIL, ALTERNATIVE_EMAIL,
  NATIONALITY, DOCUMENT_TYPE, DOCUMENT_NATIONALITY_CODE
} from '../services/mapeador_campos_miba';

export const PERFIL_MIBA_PREVISUALIZACION = {
  [FIRST_NAME]: 'Juan',
  [LAST_NAME]: 'Pérez',
  [DOCUMENT_NATIONALITY]: 'Argentina',
  [DOCUMENT_NUMBER]: 99999999,
  [GENDER]: 'M',
  [BIRTHDAY]: '1981-05-02',
  [PROVINCE]: 'Ciudad de Buenos Aires',
  [LOCATION]: 'Agronomía',
  [ADDRESS]: 'DEL LIBERTADOR AV. 8000',
  [FLOOR]: 'PB',
  [DEPARTMENT]: '2',
  [POSTAL_CODE]: '2312',
  [CODE_PHONE]: '54',
  [AREA_CODE_PHONE]: '11',
  [PHONE]: '99999999',
  [CODE_CELLPHONE]: '54',
  [AREA_CODE_CELLPHONE]: '11',
  [CELLPHONE]: '11111111',
  [CUIL]: 20999999991,
  [ALTERNATIVE_EMAIL]: 'email_alternativo@otro.com',
  [NATIONALITY]: 'Argentina',
  [DOCUMENT_TYPE]: 'DNI',
  [DOCUMENT_NATIONALITY_CODE]: 'ARG'
};
