-- DATA BASICA DE ACCESO
INSERT INTO ORGANISMO(ID, NOMBRE, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Sin Organismo', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_organismo RESTART WITH 2;



INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Sin Categoria', '0',0,'0',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 'Programacion', '0',0,'0',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(3, 'Base de Datos', '0.2',0,'2',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(4, 'Algoritmo', '0.2',0,'2',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(5, 'Algoritmo I', '0.2.4',4,'4',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(6, 'Contabilidad', '0',0,'0',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CATEGORIA(ID, NOMBRE ,NIVEL, PADRE_ID, SEQ, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(7, 'Auditoria', '0.6',0,'6',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_categoria RESTART WITH 8;



INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES(1,1,1,1);
INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES(2,1,2,1);
INSERT INTO ORGANISMO_CATEGORIA(ID,ORGANISMO_ID,CATEGORIA_ID,ESTADO)
VALUES(3,1,3,1);

ALTER SEQUENCE seq_organismo_categoria RESTART WITH 4;



INSERT INTO ROL(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Sin Rol', 'usuario sin rol ',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO ROL(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 'admin', 'usuario admin',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO ROL(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(3, 'profesor', 'usuario admin',CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_rol RESTART WITH 4;


INSERT INTO USUARIO(ID, ORGANISMO_ID, ROL_ID, CUIL, DNI, NOMBRE, APELLIDO, EMAIL, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO, PASSWORD)
VALUES(1,1,2,'123456789','000000001', 'Usuario Admin', 'Usuario Admin', 'admin@admin.com', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1,'1234');

ALTER SEQUENCE seq_usuario RESTART WITH 2;


INSERT INTO USUARIO_ORGANISMO_CATEGORIA(ID,USUARIO_ID,ORGANISMO_CATEGORIA_ID)
VALUES(1,1,1);

ALTER SEQUENCE seq_usuario_organismo_categoria RESTART WITH 2;



INSERT INTO PERMISO(ID, NOMBRE, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Sin Permiso', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_permiso RESTART WITH 2;

INSERT INTO ROL_PERMISO(ID, ROL_ID, PERMISO_ID)
VALUES(1, 1, 1);

ALTER SEQUENCE seq_permiso RESTART WITH 2;

INSERT INTO MENU(ID,RUTA, PADRE_ID, HIJO_ORDEN, BAJA, ICONO,COLOR, ESTILO, NOMBRE )
VALUES(1, 'C:documents', 1, 1, 1, 'male', 'Azul', 'Dark', 'Nuevo Menu');

ALTER SEQUENCE seq_menu RESTART WITH 2;


INSERT INTO SEDE(ID, NOMBRE, DIRECCION, PISO, EMAIL, TELEFONO, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'buenos aires', 'buenos aires', 'sin piso', 'buenosaires@correo.com', '123456789', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_sede RESTART WITH 2;

INSERT INTO CORREO(ID, NOMBRE, ASUNTO, DESCRIPCION, HTML, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'inscripciones', 'inscripcines nuevo ingreso', 'todos los alumnos', 'HTML', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_correo RESTART WITH 2;

INSERT INTO NOTIFICACION(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'plazos', 'guardado', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_notificacion RESTART WITH 2;

INSERT INTO MODALIDAD(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'vespertina', 'horario de la mañana', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_modalidad RESTART WITH 2;

INSERT INTO ESTADO(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'Curso', 'Curso', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO TIPO(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(0, 'Sin Estado', 'Sin Estado', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO TIPO(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'de inscripcion', 'de inscripcion', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO TIPO(ID, NOMBRE, DESCRIPCION, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 'Evento', 'Evento', CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_tipo RESTART WITH 2;

INSERT INTO INSCRIPCION(ID,ORGANISMO_CATEGORIA_ID,SEDE_ID,CORREO_ID,NOTIFICACION_ID,MODALIDAD_ID,TIPO_ID,ESTADO_ID,FERIADO,CUPOS_GRUPALES,LOGIN_MIBA,CANTIDAD_MAXIMA,CUPOS_INSCRIPCION,NOMBRE,URL,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES(1,1,1,1,1,1,2,1,0,10,1,50,50,'inscripcion 1','incripcion.com',CURRENT_DATE,'admin',CURRENT_DATE,'admin',1);

INSERT INTO INSCRIPCION(ID,ORGANISMO_CATEGORIA_ID,SEDE_ID,CORREO_ID,NOTIFICACION_ID,MODALIDAD_ID,TIPO_ID,ESTADO_ID,FERIADO,CUPOS_GRUPALES,LOGIN_MIBA,CANTIDAD_MAXIMA,CUPOS_INSCRIPCION,NOMBRE,URL,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES(2,1,1,1,1,1,2,1,0,10,1,50,50,'inscripcion 2','incripcion2.com',CURRENT_DATE,'admin',CURRENT_DATE,'admin',1);

INSERT INTO INSCRIPCION(ID,ORGANISMO_CATEGORIA_ID,SEDE_ID,CORREO_ID,NOTIFICACION_ID,MODALIDAD_ID,TIPO_ID,ESTADO_ID,FERIADO,CUPOS_GRUPALES,LOGIN_MIBA,CANTIDAD_MAXIMA,CUPOS_INSCRIPCION,NOMBRE,URL,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES(3,1,1,1,1,1,2,1,0,10,1,50,50,'inscripcion 3','incripcion3.com',CURRENT_DATE,'admin',CURRENT_DATE,'admin',1);

INSERT INTO INSCRIPCION(ID,ORGANISMO_CATEGORIA_ID,SEDE_ID,CORREO_ID,NOTIFICACION_ID,MODALIDAD_ID,TIPO_ID,ESTADO_ID,FERIADO,CUPOS_GRUPALES,LOGIN_MIBA,CANTIDAD_MAXIMA,CUPOS_INSCRIPCION,NOMBRE,URL,CREADO,CREADO_POR,MODIFICADO,MODIFICADO_POR,ESTADO)
VALUES(4,1,1,1,1,1,2,1,0,10,1,50,50,'inscripcion 4','incripcion4.com',CURRENT_DATE,'admin',CURRENT_DATE,'admin',1);

ALTER SEQUENCE seq_inscripcion RESTART WITH 5;

INSERT INTO INSTANCIA(ID, INSCRIPCION_ID, MODALIDAD_ID, NOMBRE, DURACION_SEMANA, LIMITE_INSCRIPCION, FECHA_INICIO, FECHA_FIN, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 1, 1, 'instancia 1', 4, CURRENT_DATE, CURRENT_DATE, CURRENT_DATE, 0, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO INSTANCIA(ID, INSCRIPCION_ID, MODALIDAD_ID, NOMBRE, DURACION_SEMANA, LIMITE_INSCRIPCION, FECHA_INICIO, FECHA_FIN, BLOQUEADO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 1, 1, 'instancia 2', 4, CURRENT_DATE, CURRENT_DATE, CURRENT_DATE, 0, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_instancia RESTART WITH 2;

INSERT INTO CLASE_SEDE(ID, INSTANCIA_ID, SEDE_ID, NOMBRE, CUPOS, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FECHA, HORA_INICIO, HORA_FIN, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 1, 1, 'claseSede 1', 30, 1, 1, 1, 1, 1, 0, 0, CURRENT_DATE, CURRENT_TIME, CURRENT_TIME, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

INSERT INTO CLASE_SEDE(ID, INSTANCIA_ID, SEDE_ID, NOMBRE, CUPOS, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FECHA, HORA_INICIO, HORA_FIN, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(2, 1, 1, 'claseSede 2', 30, 0, 0, 0, 0, 0, 1, 1, CURRENT_DATE, CURRENT_TIME, CURRENT_TIME,CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_clase_sede RESTART WITH 2;

INSERT INTO FORMULARIO(ID, NOMBRE, DESCRIPCION, ID_REF_MONGO, CREADO, CREADO_POR, MODIFICADO, MODIFICADO_POR, ESTADO)
VALUES(1, 'formulario de test', 'formulario de test', 1, CURRENT_DATE, 'admin', CURRENT_DATE, 'admin', 1);

ALTER SEQUENCE seq_formulario RESTART WITH 2;

INSERT INTO FORMULARIO_INSCRIPCION(ID, inscripcion_id, formulario_id)
VALUES(1, 1, 1);

ALTER SEQUENCE seq_formulario_inscripcion RESTART WITH 2;

